import unittest
from contextlib import contextmanager

#Implementation of assertRaisesMessage from django 2
class SimpleTest(unittest.TestCase):    
   
    @contextmanager
    def _assert_raises_or_warns_cm(self, func, cm_attr, expected_exception, expected_message):
        with func(expected_exception) as cm:
            yield cm
        self.assertIn(expected_message, str(getattr(cm, cm_attr)))

    def _assertFooMessage(self, func, cm_attr, expected_exception, expected_message, *args, **kwargs):
        callable_obj = None
        if args:
            callable_obj, *args = args
        cm = self._assert_raises_or_warns_cm(func, cm_attr, expected_exception, expected_message)
        # Assertion used in context manager fashion.
        if callable_obj is None:
            return cm
        # Assertion was passed a callable.
        with cm:
            callable_obj(*args, **kwargs)

    def assertRaisesMessage(self, expected_exception, expected_message, *args, **kwargs):
        """
        Assert that expected_message is found in the message of a raised
        exception.

        Args:
            expected_exception: Exception class expected to be raised.
            expected_message: expected error message string value.
            args: Function to be called and extra positional args.
            kwargs: Extra kwargs.
        """
        return self._assertFooMessage(
            self.assertRaises, 'exception', expected_exception, expected_message,
            *args, **kwargs
        )